# Website information
site_name: Cytoscape 中文用户手册
site_url: https://cytosacpe.leovan.tech
site_author: 范叶亮 | Leo Van
site_description: Cytoscape 中文用户手册

# Repository
repo_name: leovan/cytoscape-manual
repo_url: https://github.com/leovan/cytoscape-manual
edit_uri: edit/main/docs/

# Copyright
copyright: 翻译：<a href="https://leovan.me" target="_blank">范叶亮 | Leo Van</a>

# Navigation
nav:
  - 主页: index.md
  - 简介: introduction.md
  - 启动 Cytoscape: launching-cytoscape.md
  - 命令行参数: command-line-arguments.md
  - 快速教程: quick-tour-of-cytoscape.md
  - 创建网络: creating-networks.md
  - 嵌套网络: nested-networks.md
  - 支持的网络文件格式: supported-network-file-formats.md
  - 节点和边列数据: node-and-edge-column-data.md
  - 列数据函数和方程: column-data-functions-and-equations.md
  - 搜索和过滤节点和边: finding-and-filtering-nodes-and-edges.md
  - 导航和布局: navigation-and-layout.md
  - 样式: styles.md
  - 网络注释: annotations.md
  - 应用商店: app-store.md
  - 命令面板: command-panel.md
  - 网页浏览器: web-browser.md
  - 合并: merge.md
  - 网络分析器: network-analyzer.md
  - 富集表格: enrichment-table.md
  - 首选项: preferences.md
  - Linkout: linkout.md
  - 面板: panels.md
  - 渲染引擎: rendering-engine.md
  - 数据导出: export-your-data.md
  - Cytoscape 和 OpenCL: cytoscape-and-opencl.md
  - Cytoscape.js 和 Cytoscape: cytoscape-js-and-cytoscape.md
  - 自动化: automation.md
  - 隐私政策: privacy-policy.md
  - 基础分析教程: basic-expression-analysis-tutorial.md

# Theme
theme:
  name: material
  include_search_page: false
  search_index_only: true
  language: zh
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: 暗黑
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/white-balance-sunny
        name: 明亮
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/cytoscape3-icon.png
  logo: images/cytoscape3-icon.png

# Plugins
plugins:
  - search:
      lang: en

# Extra
extra:
  social:
    - icon: material/home
      link: https://leovan.me
      name: 个人主页
    - icon: material/github
      link: https://github.com/leovan
      name: Github
  analytics:
    provider: google
    property: G-7TZ9SS38QN
extra_css:
  - css/image.css
  - css/table.css
extra_javascript:
  - js/math.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: leovan
      repo: cytoscape-manual
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde